### ISSUE TITLE
Comprehension question

### ISSUE THREAD

**Issue by tempo-riz** [SNNafi/media_store_plus#23]
Hey ! I'm new to the mediastore API, my goal is to read whatsapp files under '/storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Audio/' with API 33+and i'm confused, are those available via the audio dirType ? Or not ?

To read files via the media store is the only way to first create a tmp file and then copy to it ? Because that would need to duplicate every file we want to read :/

Hope you can help ! Thanks for this package :)

**Comment by afghandev5** [comment]
I have the same issue, I'm struggling with this problem how we can delete files from desired folders because the API that provided by the media_store_plus is so poor. I mean if u want to delete files from desired folder something like this android/emulate/0/Songs/AnotherFolder/124.mp3 then there's no way to do that!!! 

I want from you @SNNafi if there is any way for deleting files from desired folders please help me???

**Comment by SNNafi** [comment]
@afghandev5  There is no directory called **Songs** in MediaStore collections.  
Here are the directories that are available with MediaStore API. https://developer.android.com/training/data-storage/shared/media

You can't use any other directory with MediaStore API besides these directories.

**Comment by SNNafi** [comment]
@tempo-riz , the doc text is wrong. Please check the function signature to understand the function. I will update the doc text.

No, you can't. Here are the directories that are available with MediaStore API, https://developer.android.com/training/data-storage/shared/media

**Comment by SNNafi** [comment]
However, there is a method called `requestForAccess()` to request access to particular files and it returns `DocumentTree`. That contains `uriString`. 

Then you can use `deleteFileUsingUri()` with the `URI` to delete the file.
